#!/bin/bash

. ../setup.conf
. /usr/local/lib/$RPI_DEV_GROUP/functions/color_text

# Set locale to en_US.UTF-8
LOCALE="en_US.UTF-8"
ENCODING="UTF-8"
println "$(date) [INFO] Setting locale:$LOCALE and encoding:$ENCODING" "green"
# /etc/default/locale
cat >> /etc/default/locale << EOF
LANG=$LOCALE
LANGUAGE=$LOCALE
LC_ALL=C
LC_CTYPE=C
EOF
# debconf locale select
cat << EOF | debconf-set-selections
locales locales/locales_to_be_generated multiselect $LOCALE $ENCODING
EOF
rm /etc/locale.gen
dpkg-reconfigure -f noninteractive locales
update-locale LANG="$LOCALE"
cat << EOF | debconf-set-selections
locales locales/default_environment_locale select $LOCALE
EOF

# Set the keyboard to US, don't set any modifier keys
KEYMAP="us"
println "$(date) [INFO] Setting keyboard layout: $KEYMAP" "green"
sed -i /etc/default/keyboard -e "s/^XKBLAYOUT.*/XKBLAYOUT=\"$KEYMAP\"/"
dpkg-reconfigure -f noninteractive keyboard-configuration

# Enable serial console
println "$(date) [INFO] Enabling serial console" "green"
echo "enable_uart=1" >> /boot/config.txt
