#!/bin/bash
. ../setup.conf
. /usr/local/lib/$RPI_DEV_GROUP/functions/color_text

println "$(date) [TRACE] Installing ufw packages" "green"
DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --yes ufw 1> /dev/null

println "$(date) [TRACE] Modifying UFW defaults" "green"
sed -i 's|^IPV6=.*|IPV6=no|g' /etc/default/ufw

println "$(date) [TRACE] Adding ufw rules" "green"
# default rules
chmod +x ufw-default-rules
./ufw-default-rules

# port specific rules
chmod +x ufw-add-rules
./ufw-add-rules
